server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  profiles:
    active: dev
  config:
    import: classpath:discord-token.yml, classpath:mongo-config.yml
  data:
    mongodb:
      uri: ${mongo.uri}
      database: ${mongo.database}

logging:
  level:
    root: info

jda:
  token: ${discord.token}